parameters:
    viz_root_path: /VIZ-SET
    viz_set:
        '00': ['00', '15', '32', '53']
        '01': ['01', '16']
        '02': ['02', '36']
        '03': ['03', '18', '26', '29']
        '04': ['04', '19', '37']
        '05': ['05', '20', '38']
        '06': ['06', '21', '39', '40']
        '07': ['07', '22', '41', '42', '43']
        '08': ['08', '23', '44']
        '09': ['09', '45']
        '10': ['10']
        '11': ['11', '24']
        '12': ['12', '25', '46', '54']
        '13': ['13']
        '14': ['14']
        '48': ['28', '47', '48', '52']
        '49': ['34', '35', '49']
        '50': ['17', '33', '50']
        '51': ['27', '30', '31', '51']