pimcore:
    general:
        domain: "%env(APP_DOMAIN)%"
        redirect_to_maindomain: false
        valid_languages:
            - en
            - pl
        fallback_languages:
            en: pl
            pl: ''
        required_languages:
            - en
            - pl
        default_language: pl
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: 8
        error_pages:
            default: ''
            localized:
                en: ''
                pl: ''
    objects:
        versions:
            days: null
            steps: 64
    assets:
        versions:
            days: null
            steps: 8
    email: {  }
